FROM resin/%%RESIN_MACHINE_NAME%%-python:2.7-slim

WORKDIR /usr/src/app

COPY ./app/requirements.txt ./

RUN apt-get update && apt-get install -yq --no-install-recommends \
  sense-hat \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./app ./

## Uncomment if you want systemd
ENV INITSYSTEM on

# Start app
CMD ["python", "/usr/src/app/app.py"]
